#!/bin/bash

#ant

#java -XX:+FlightRecorder -XX:StartFlightRecording=duration=100s,filename=./flight.jfr -cp lib/util.jar:lib/cl.jar rf.configtool.main.Main $*

java -cp ./target/cft-latest.jar rf.configtool.main.Main $*
